name: application-terraform-apply

on:
  push:
  workflow_dispatch:
    inputs:
      tfvars_path:
        type: string
        required: true
        description: ""

env:
  tfvars_path: ${{ inputs.tfvars_path }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: handle push commit
        run: |
          file_path=$(echo "${{github.event.head_commit.message}}" | awk -F "#tfvars_path=" '{print $2}' | awk '{print $1}')
          echo "tfvars_path=$file_path" >> $GITHUB_ENV
        if: contains(github.event.head_commit.message, '#tfvars_path=')
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform select workspace
        id: select
        run: |
          workspace=$(basename ${{ env.tfvars_path }} | cut -d "." -f 1)
          terraform workspace select $workspace || terraform workspace new $workspace

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -no-color -lock=false --auto-approve -var-file="${{ env.tfvars_path }}" 

