name: application-terraform-apply

on:
  push:
  workflow_dispatch:
    inputs:
      tfvars_path:
        type: string
        required: true
        description: ""

env:
  tfvars_path: ${{ inputs.tfvars_path }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: handle push commit
        run: |
          file_path=$(echo "${{github.event.head_commit.message}}" | awk -F "#tfvars_path=" '{print $2}' | awk '{print $1}')
          echo "tfvars_path=$file_path" >> $GITHUB_ENV
        if: contains(github.event.head_commit.message, '#tfvars_path=')
      - name: handle push commit2
        run: |
          tf_command=$(echo "${{github.event.head_commit.message}}" | awk -F "#tf_command=" '{print $2}' | awk '{print $1}')
          echo "tf_command=$tf_command" >> $GITHUB_ENV
        if: contains(github.event.head_commit.message, '#tf_command=')
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform select workspace
        id: select
        run: |
          workspace=$(basename ${{ env.tfvars_path }} | cut -d "." -f 1)
          terraform workspace select $workspace || terraform workspace new $workspace

      - name: Terraform Apply destroy
        id: apply
        run: |
          if [ -z $tf_command ] ; then
            tf_command="apply"
          fi
          if [ "$tf_command" = "remove" ] ; then
            to_remove="true"
            tf_command="destroy"
          fi
          terraform $tf_command -no-color -lock=false --auto-approve -var-file="${{ env.tfvars_path }}" 
          if [ "$to_remove" = 'true' ] ; then
            rm -f $tfvars_path
            git commit -am "remove $tfvars_path by skygen"
            git push
          fi
